### ISSUE TITLE
ERROR: Application reached its maximum number of concurrent connections. 

### ISSUE THREAD

**Issue by stan-radu-andrei** [realtime-framework/RealtimeRxJS#1]
Application reached its maximum number of concurrent connections. 
When this error appears notifications doesn't work. The error doesn't appear every time. What can cause it?

**Comment by realtime-framework** [comment]
This errors means that you have reached the maximum number of concurrent (simultaneous) connections for your Realtime application key. Please consider upgrading.

**Comment by stan-radu-andrei** [comment]
How is this? I am pretty sure I don't have 100 users on my app, as we are
still developing.

On Fri, Feb 2, 2018 at 8:19 PM, Realtime Framework <notifications@github.com

**Comment by realtime-framework** [comment]
Please check if you are not creating several connections for each user
